version: '3'

networks:
  proxy:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - proxy

  proxy:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - proxy