version: '3'

networks:
  proxy:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - proxy

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - proxy_app
    ports:
      - "4000:4000"
    networks:
      - proxy

  proxy_app:
    build: ./proxy
    ports:
      - "5000"
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 6

  metrics:
    build: ./metrics
    ports:
      - "5000"
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - proxy
